services:
  rebecca-node:
    # build: .
    image: rebeccapanel/rebecca-node:latest
    restart: always
    network_mode: host

    # env_file: .env
    environment:
      SSL_CERT_FILE: "/var/lib/rebecca-node/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/rebecca-node/ssl_key.pem"
      # SSL_CLIENT_CERT_FILE: "/var/lib/rebecca-node/ssl_client_cert.pem"

    volumes:
      - /var/lib/rebecca-node:/var/lib/rebecca-node
